### ISSUE TITLE
DBusConnection timeout

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#63] opened 2019-05-20 13:55 UTC
During the creation of a dbus connection I can pass a timeout. After that timeout of inactivity on the connection it dies (and never reconnects since it's fatal) with:
```
15:51:27.766 [DBusConnection] ERROR o.f.d.c.IncomingMessageThread - FatalException in connection thread.
org.freedesktop.dbus.exceptions.FatalDBusException: Underlying transport returned EOF (1)
	at org.freedesktop.dbus.connections.AbstractConnection.readIncoming(AbstractConnection.java:1102)
	at org.freedesktop.dbus.connections.IncomingMessageThread.run(IncomingMessageThread.java:39)
```
I guess that's not expected?

Can be reproduced on any test by setting a breakpoint after connection creation (default timeout is 100 sek).

**Comment by hypfvieh** [comment] 2019-05-20 14:13
No that is not the intended behaviour. I guess that this has something to do with the pull request which added the timeout stuff ..

**Comment by lbeuster** [comment] 2019-05-20 14:48
Currently this timeout is used as the read timeout on the connection. Is that really needed? Maybe it makes more sense to have a connect timeout (at least for TCP - don't know if this is useful for domain sockets)?

**Comment by hypfvieh** [comment] 2019-05-20 15:37
I think setting a read timeout on the InputStream is not really useful at all (weird behaviour).
There might be no answer for a long time, so closing the stream after a minute or so would not be suitable for any usage.

As you said, a connect timeout is useful at least for TCP.

On unix sockets, I cannot imagine any configuration that would benefit from a connect timeout.
If there is a permissioning issue, the connection will fail immediately.
If there is no socket file at all, connection also fails instantly.

If you like you can fix it, then I'll merge your PR tomorrow, otherwise I'll take a look at it tomorrow.

**Comment by lbeuster** [comment] 2019-05-20 15:43
I'll leave it for you since since I'm not quite sure what to do with the timeout ;)

**Comment by hypfvieh** [comment] 2019-05-21 06:15
I've changed the timeout stuff. Timeout will now only be used when using TCP socket and only for the connect method (to set the timeout before connection attempt fails). 

All other options do not make sense at all. Stop reading on the InputStream after X seconds is not useful in any way. It would only make sense if DBus would use some sort of heartbeating system, but there isn't something like that.

**Comment by lbeuster** [comment] 2019-05-21 15:16
Thanks, works.

**Closed** 2019-05-22 05:00 UTC
